apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: amigos
  name: customer
spec:
  selector:
    matchLabels:
      app: customer
      tier: backend
      version: "1"
  template:
    metadata:
      labels:
        app: customer
        tier: backend
        version: "1"
    spec:
      containers:
      - name: customer
        image: amigoscode/kubernetes:customer-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
            - name: ORDER_SERVICE
              value: "order"

---

apiVersion: v1
kind: Service
metadata:
  namespace: amigos
  name: customer
spec:
  selector:
    app: customer
    tier: backend
    version: "1"
  ports:
  - port: 80
    targetPort: 8080

