apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: amigos
  name: order
spec:
  selector:
    matchLabels:
      app: order
      tier: backend
      version: "1"
  template:
    metadata:
      labels:
        app: order
        tier: backend
        version: "1"
    spec:
      containers:
      - name: order
        image: amigoscode/kubernetes:order-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  namespace: amigos
  name: order
spec:
  selector:
    app: order
    tier: backend
    version: "1"
  ports:
  - port: 80
    targetPort: 8081

